import type { Metadata } from "next";
import "./globals.css";
import { ServerStylePreview } from "typedcssx/next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ServerStylePreview />
      </head>
      <body>{children}</body>
    </html>
  );
}
